#!/bin/bash
MENU() {
clear
echo -e "\e[1;33m   █████████                       █████                        █████"
echo -e "  ███░░░░░███                     ░░███                        ░░███"
echo -e " ███     ░░░   ██████  ████████   ███████    ██████    ██████  ███████"
echo -e "░███          ███░░███░░███░░███ ░░░███░    ░░░░░███  ███░░███░░░███░"
echo -e "░███         ░███ ░███ ░███ ░███   ░███      ███████ ░███ ░░░   ░███"
echo -e "░░███     ███░███ ░███ ░███ ░███   ░███ ███ ███░░███ ░███  ███  ░███ ███"
echo -e " ░░█████████ ░░██████  ████ █████  ░░█████ ░░████████░░██████   ░░█████"
echo -e "  ░░░░░░░░░   ░░░░░░  ░░░░ ░░░░░    ░░░░░   ░░░░░░░░  ░░░░░░     ░░░░░"
echo -e "			\e[1;34m ██████   ██████"
echo -e "			░░██████ ██████"
echo -e "			 ░███░█████░███   ██████"
echo -e "			 ░███░░███ ░███  ███░░███"
echo -e "			 ░███ ░░░  ░███ ░███████"
echo -e "			 ░███      ░███ ░███░░░"
echo -e "			 █████     █████░░██████"
echo -e "			░░░░░     ░░░░░  ░░░░░░"
echo -e "			\e[1;33m[\e[1;31m+\e[1;33m] \e[1;36mCoaded By Darken-Pasiya"
echo -e "			\e[1;33m[\e[1;31m+\e[1;33m] \e[1;36mGithub.com/Darken-Pasiya"
echo -e ""
echo -e '\e[1;37m
╔════╦══════════════╦════╗
║          \e[1;33;1;44mMENU\e[0m\e[1;37m          ║
╠╦═══╩══════════════╩════╝
║║
║║
║╠══⏩ [[ \e[1;37;1;41m01\e[0m ]] \e[1;33mWA.ME Link\e[1;37m
║║
║╠══⏩ [[ \e[1;37;1;41m02\e[0m ]] \e[1;34mWA Direct Message Link\e[1;37m
║║
║╠══⏩ [[ \e[1;37;1;41m03\e[0m ]] \e[1;35mWA Group Link To Forwed Link\e[1;37m
║║
║╠══⏩ [[ \e[1;37;1;41m04\e[0m ]] \e[1;36mCustom URL Creator\e[1;37m
║║
║╠══⏩ [[ \e[1;37;1;41m05\e[0m ]] \e[1;32mShort Any URL\e[1;37m
║║
║╠══⏩ [[ \e[1;37;1;41m06\e[0m ]] \e[1;31mTemporary Mail\e[1;37m
║║
║╠══⏩ [[ \e[1;37;1;41m00\e[0m ]] \e[1;37mExit
║║
║║
║╚════\e[1;37;1;41mDARKEN\e[0m::\e[1;37;1;41mPASIYA\e[0m\e[1;37m═════╗
╚════════════════════════╝'
}
selec() {
echo ""
echo ""
echo -e "\e[1;36m┏━━\e[1;35mDarken\e[1;36m-\e[1;35mPasiya\e[1;36m━\e[1;33m▶"
echo -e "\e[1;36m┃"
read -p $'\e[1;36m┗━━\e[1;32mContact\e[1;36m━━━\e[1;32mMe\e[1;36m━━\e[1;33m▶ ' chose
if [[ $chose = 1 || $chose = 01 ]]; then
Wame
elif [[ $chose = 2 || $chose = 02 ]]; then
Direct
elif [[ $chose = 3 || $chose = 03 ]]; then
Group
elif [[ $chose = 4 || $chose = 04 ]]; then
Custom
elif [[ $chose = 5 || $chose = 05 ]]; then
Any
elif [[ $chose = 6 || $chose = 06 ]]; then
Temp
else
sleep 1
exit
fi
}
Wame() {
echo
echo
echo -e "\e[1;34mex : \e[1;33m+94761234567 \e[1;36m/ \e[1;33m94761234567"
read -p $'\e[1;35mEnter Your Number With Country Code : \e[1;36m' wame
sleep 1
echo
echo
echo -e "\033[1;34m┏━━━━━━━━━━\033[1;36mCOPY LINK\033[1;34m━━━━━━━━━━┓"
echo -e "┃"
echo -e "┣━┳━[\033[1;47;31m  Direct Link  \033[0m]\033[1;34m"
echo -e "┣━┻━▶  \033[1;32mwa.me/"$wame
echo -e "\033[1;34m┃"
echo -e "\e[1;34m┣━┳━[\033[1;47;31m  Web Link  \033[0m]\033[1;34m"
echo -e "┣━┻━▶  \033[1;32mhttps://wa.me/"$wame
echo -e "\033[1;34m┃"
echo -e "┗━━━━━━━━━━\033[1;36mCOPY LINK\033[1;34m━━━━━━━━━━┛"
echo -e ""
echo
read -p $'\e[1;33mIf You Want Continue \e[1;36mY/N\e[1;37m : ' con
if [[ $con = y || $con = Y ]]; then
MENU
selec
else
echo
echo
sleep 1
exit
fi
}
Direct() {
echo -e""
echo -e""
echo -e "\e[1;34m ex: \e[1;33m+94761234567 \e[1;36m/ \e[1;33m94761234567"
echo -e""
read -p $'  \033[1;32mEnter Your Phone Number With Country Code :  \033[1;33m' numb
echo -e""
echo -e "\e[1;34m┏━\e[34m[\e[1;31m+\e[1;34m]\e[1;31m Dont Use Space .\e[1;33m please use ▶ \e[1;36m%20\e[1;33m ◀ For Space "
echo -e "\e[1;34m┃"
Numb=("https://api.whatsapp.com/send?phone=%22"$numb)
read -p $'\e[1;34m┗━━\033[1;32mEnter Your Whatsapp Massege :\033[1;36m  ' msg
git=($Numb"%22&text="$msg)
link=$git
final=$(curl -s http://tinyurl.com/api-create.php?url=$link)
echo -e""
echo -e "\e[1;33m                        .....Processing....."
echo -e""
echo -e""
sleep 2
echo -e "\e[90m                ╔══════════════Darken Pasiya════════════╗"
echo -e "\e[90m                ║ ╔═══════════════════════════════════╗ ║"
echo -e ""
echo -e "\e[1;33m                       "$final
echo -e ""
echo -e "\e[90m                ║ ╚═══════════════════════════════════╝ ║"
echo -e "\e[90m                ╚══════════════Darken Pasiya════════════╝"
echo -e""
echo -e""
echo -e""
echo
read -p $'\e[1;33mIf You Want Continue \e[1;36mY/N\e[1;37m : ' cot
if [[ $cot = y || $cot = Y ]]; then
MENU
selec
else
echo
echo
sleep 1
exit
fi
}
Group() {
echo
echo
read -p $'\e[1;33m   Enter Whatsapp Group Link :  \e[1;36m' group
sleep 1
linkg=("https://api.whatsapp.com/send?text="$group)
Glink=$(curl -s http://tinyurl.com/api-create.php?url=$linkg)
echo
echo
echo -e "\e[1;34m┏━━━━━━━━━━\e[1;36mCOPY LINK\e[1;34m━━━━━━━━━━┓"
echo -e "┃"
echo -e "┣━┳━[\e[1;47;31m  Direct Link  \e[0m]\e[34m"
echo -e "┗━┻━▶  \e[1;32mhttps://api.whatsapp.com/send?text="$group
echo -e "\e[1;34m┏━┳━[\e[1;47;31m  Web Link  \e[0m]\e[34m"
echo -e "┣━┻━▶  \e[1;32m"$Glink
echo -e "\e[34m┃"
echo -e "┗━━━━━━━━━━\e[36mCOPY LINK\e[34m━━━━━━━━━━┛"
echo -e""
echo
read -p $'\e[1;33mIf You Want Continue \e[1;36mY/N\e[1;37m : ' cos
if [[ $cos = y || $cos = Y ]]; then
MENU
selec
else
echo
echo
sleep 1
exit
fi
}
Custom() {
echo
echo
url_checker() {
if [ ! "${1//:*}" = http ]; then
if [ ! "${1//:*}" = https ]; then
echo -e "\e[1;31m[\e[1;33m!\e[1;31m] Invalid URL. Please use \e[1;33mhttp \e[1;31mor \e[1;33mhttps.\e[0m"
exit 1
fi
fi
}
echo -e "\e[1;36mPaste Phishing URL Or Any URL here (\e[1;33mwith http or https\e[1;36m): "
read phish
url_checker $phish
MENU
sleep 1
echo
echo -e "           \e[1;32mProcessing and Modifing Your URL"
echo ""
short=$(curl -s https://is.gd/create.php\?format\=simple\&url\=${phish})
shorter=${short#https://}
echo -e "\n                  \e[1;33;44m ### Modifing ###\e[0m"
sleep 1
echo ""
echo -e "  Domain to mask the Phishing URL (\e[1;33mwith http or https\e[0m)"
echo -e " ex: \e[1;35mhttps://google.com\e[0m"
echo -e "     \e[1;35mhttp://Darken-Pasiya.com\e[0m"
echo -e "     \e[1;35mhttps://Ehi-Master"
echo ""
echo -en "\e[37m~/\e[1;32m$\e[1;37m@\e[1;32mroot\e[1;37m@\e[1;32mContact-Me\e[1;37m~>\e[1;36m "
read Cust
url_checker $Cust
MENU
sleep 0.5
echo -e '\n\e[1;37mType social engineering words:( \e[1;33mfree-money, best-pubg-tricks\e[0m)'
echo -e "\e[1;36mDon't use space just use '\e[1;33m-\e[1;36m' between social engineering words\e[0m"
echo
echo -en "\e[37m~/\e[1;32m$\e[1;37m@\e[1;32mroot\e[1;37m@\e[1;32mContact-Me\e[1;37m~>\e[36m "
read words
if [[ -z "$words" ]]; then
echo -e "\e[31m[!] No words.\e[0m"
echo -e "\nGenerating Custom Domain Link...\n"
final=$Cust@$shorter
sleep 1
echo -e "\e[1;33mYour Custom Domain URL:\e[36m ${final} \e[0m\n"
exit
fi
if [[ "$words" =~ " " ]]; then
echo -e "\e[31m[!] Invalid words. Please avoid space.\e[0m"
echo -e "\n\e[1;32mGenerating Custom Domain Link...\n"
final=$Cust@$shorter
sleep 1
echo -e "\e[1;33mYour Custom Domain URL:\e[36m ${final} \e[0m\n"
exit
fi
echo -e "\n\e[1;32mGenerating Custom Domain Link...\n"
sleep 2
echo ""
final=$Cust-$words@$shorter
sleep 1
echo -e "\e[1;33mYour Custom Domain URL:\e[36m ${final} \e[0m\n"
echo
}
Any() {
echo
echo
read -p $'\e[1;33mEnter Your URL : \e[1;36m' any
echo
echo
final=$(curl -s http://tinyurl.com/api-create.php?url=$any)
echo -e""
echo -e "\e[1;33m                        .....Processing....."
echo -e""
echo -e""
sleep 2
echo -e "\e[90m                ╔══════════════Darken Pasiya════════════╗"
echo -e "\e[90m                ║ ╔═══════════════════════════════════╗ ║"
echo -e ""
echo -e "\e[1;33m                       "$final
echo -e ""
echo -e "\e[90m                ║ ╚═══════════════════════════════════╝ ║"
echo -e "\e[90m                ╚══════════════Darken Pasiya════════════╝"
echo -e""
echo -e""
echo -e""
echo
read -p $'\e[1;33mIf You Want Continue \e[1;36mY/N\e[1;37m : ' cok
if [[ $cok = y || $cok = Y ]]; then
MENU
selec
else
echo
echo
sleep 1
exit
fi
}
Temp() {
echo
echo
echo -e "\e[1;36m Type \e[1;33mTemporary \e[1;36mAnd Press Enter For Run"
echo
echo
}
figlet wait | lolcat
cd $HOME > /dev/null 2>&1
rm -rf Contact-Me > /dev/null 2>&1
git clone https://github.com/Darken-Pasiya/Contact-Me > /dev/null 2>&1
cd Contact-Me > /dev/null 2>&1
MENU
selec
