#!/bin/python
# Tempory Mail

import os
import subprocess
import random
import sys
import colorama
import pyfiglet

try:
	import requests as r, random, json, os
	from time import sleep
except ModuleNotFoundError:
	exit("[!] Module not installed")

list_mail = ["labworld.org","vintomaper.com","mentonit.net"]
url = "https://cryptogmail.com/"
num = 0

file_path = "pas.txt"
pass_file = open(file_path,'r')
pass_list = pass_file.readlines()
i = 0
for paso in pass_list:
 i = i + 1

def get_teks(accept, key):
	cek = r.get(url+"api/emails/"+key, headers={"accept": accept}).text
	if "error" in cek:
		return "-"
	else:
		return cek.strip()

def get_random(digit):
	lis = list("abcdefghijklmnopqrstuvwxyz0123456789")
	dig = [random.choice(lis) for _ in range(digit)]
	return "".join(dig), random.choice(list_mail)

def animate(teks):
	lis = list("543210")
	for cy in lis:
		print("\r\033[1;34m[\033[1;33m"+cy+"\033[1;34m] "+str(teks)+"\033[1;34m[\033[1;33m"+cy+"\033[1;34m]", end="")
		sleep(1)

def run(email):
	while True:
		try:
			animate('\033[1;35mWaiting for incoming message')
			raun = r.get(url+"api/emails?inbox="+email).text
			if "404" in raun:
				continue
			elif "data" in raun:
				z = json.loads(raun)
				for data in z["data"]:
					new = ' 📩 \033[1;36mReceived New Mail 📩'
					_ = int(os.get_terminal_size().columns/2)
					_ -= int(len(new)/2)
					print()
					print('\n' + '\033[1;37m.' * _ +  new  + '\033[1;37m.' * _ + '\n')
					print()
					print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mID: \033[1;33m"+data["id"], end="\n")
					got = json.loads(r.get(url+"api/emails/"+data["id"]).text)
					pengirim = got["data"]["sender"]["display_name"]
					email_pe = got["data"]["sender"]["email"]
					subject  = got["data"]["subject"]
					print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mSender Name: \033[1;33m"+pengirim, end="\n")
					print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mSender mail: \033[1;33m"+email_pe, end="\n")
					print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mSubject    : \033[1;33m"+subject, end="\n")
					print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mMessage    :\033[1;33m "+get_teks("text/html,text/plain",data["id"]), end="\n")
					atc = got["data"]["attachments"]
					if atc == []:
						print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mattachments: -\033[1;33m", end="\n")
					else:
						print("[•] attachments: ")
						for atch in atc:
							id = atch["id"]
							name = atch["file_name"]
							name = name.split(".")[-1]
							svee = r.get("https://cryptogmail.com/api/emails/"+data["id"]+"/attachments/"+id)
							open(id+"."+name, "wb").write(svee.content)
							print("      ~ "+id+"."+name)
					_ = int(os.get_terminal_size().columns/2)
					print()
					print('╍' *os.get_terminal_size().columns + '\n')
					r.delete(url+"api/emails/"+data["id"])
				continue
			else:
				continue
		except (KeyboardInterrupt,EOFError):
				exit("\n\033[1;34m[\033[1;32m✓\033[1;34m] \033[1;32mProgram finished, \033[1;33mexiting...\n")


def main():

	BLU = colorama.Style.BRIGHT + colorama.Fore.BLUE
	CYA = colorama.Style.BRIGHT + colorama.Fore.CYAN
	GRE = colorama.Style.BRIGHT + colorama.Fore.GREEN
	YEL = colorama.Style.BRIGHT + colorama.Fore.YELLOW
	RED = colorama.Style.BRIGHT + colorama.Fore.RED
	MAG = colorama.Style.BRIGHT + colorama.Fore.MAGENTA
	LIYEL = colorama.Style.BRIGHT + colorama.Fore.LIGHTYELLOW_EX
	LIRED = colorama.Style.BRIGHT + colorama.Fore.LIGHTRED_EX
	LIMAG = colorama.Style.BRIGHT + colorama.Fore.LIGHTMAGENTA_EX
	LIBLU = colorama.Style.BRIGHT + colorama.Fore.LIGHTBLUE_EX
	LICYA = colorama.Style.BRIGHT + colorama.Fore.LIGHTCYAN_EX
	LIGRE = colorama.Style.BRIGHT + colorama.Fore.LIGHTGREEN_EX
	BOLD = colorama.Style.BRIGHT
	CLEAR = 'cls' if os.name == 'nt' else 'clear'
	COLORS = BLU, CYA, GRE, YEL, RED, MAG, LIYEL, LIRED, LIMAG, LIBLU, LICYA, LIGRE
	FONTS = 'basic', 'o8', 'cosmic', 'graffiti', 'chunky', 'epic', 'doom', 'avatar', 'poison', 'banner3-D', 'usaflag', 'alligator2', 'fraktur', 'nancyj-fancy', 'r2-d2___', 'whimsy'
	global font
	global num
	font = random.choice(FONTS)
	colorama.init(autoreset=True)


	os.system(CLEAR)
	color1 = random.choice(COLORS)
	color2 = random.choice(COLORS)
	color3 = random.choice(COLORS)
	color4 = random.choice(COLORS)
	while color1 == color2:
	    color2 = random.choice(COLORS)
	repo = '[+] From Cotact Me'
	_ = int(os.get_terminal_size().columns/2)
	_ -= int(len(repo)/2)
	print(color1 + '═' * _ + color3 + repo + color1 + '═' * _ + '\n')
	print(color2 + pyfiglet.figlet_format('Temp\nMail', font=font, justify='center', width=os.get_terminal_size().columns), end='\n')
	msg = '[+] By Darken Pasiya'
	_ = int(os.get_terminal_size().columns/2)
	_ -= int(len(msg)/2)
	print(color1 + '═' * _ + color3 + msg + color1 + '═' * _ )
	print("""




\033[1;34m┏━━\033[1;32m▶\033[1;34m[\033[1;37;41m01\033[0m\033[1;34m] \033[1;33mGET RANDOM EMAIL
\033[1;34m┃
\033[1;34m┣━━\033[1;32m▶\033[1;34m[\033[1;37;41m02\033[0m\033[1;34m] \033[1;33mCREATE CUSTOM EMAIL
\033[1;34m┃
\033[1;34m┗━━\033[1;32m▶\033[1;34m[\033[1;37;41m00\033[0m\033[1;34m] \033[1;37mEXIT\033[0m



""" )


	pil = input("~\033[1;32m/$\033[1;37m@\033[1;36mroot\033[1;37m@\033[1;36mTemporary-Mail\033[1;37m~\033[1;33m>\033[1;37m ")
	while pil == "" or not pil.isdigit():
		pil = input("~\033[1;32m/$\033[1;37m@\033[1;36mroot\033[1;37m@\033[1;36mTemporary-Mail\033[1;37m~\033[1;33m>\033[1;37m ")
	if pil in ["01","1"]:
		set_name, set_email = get_random(10)
		print("\n\033[1;34m[\033[1;32m*\033[1;34m] \033[1;32mYour email: \033[1;33m"+set_name+"-darkenpasiya"+"@"+set_email)
		print("\033[1;34m[\033[1;31m*\033[1;34m] \033[1;36mCTRL+ C \033[1;31mto stopped..\033[1;37m")
		_ = int(os.get_terminal_size().columns/2)
		print('╍' * os.get_terminal_size().columns + '\n')
		run(set_name+"-darkenpasiya"+"@"+set_email)
	elif pil in ["02","2"]:
		print()
		set_name = input("\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mSet mail name:\033[1;36m ")
		print()
		for cy in list_mail:
			num += 1
			print(" "*5,"\033[1;34m[\033[1;32m"+str(num)+"\033[1;34m]\033[1;33m @"+cy)
		print()
		set_email = input("\033[1;34m[\033[1;33m?\033[1;34m] \033[1;35mSelect: \033[1;36m")
		while set_email == "" or not set_email.isdigit() or int(set_email) > len(list_mail):
			set_email = input("\033[1;34m[\033[1;33m?\033[1;34m] \033[1;35mSelect:\033[1;36m ")
		mail = list_mail[int(set_email)-1]
		print("\n\033[1;34m[\033[1;32m*\033[1;34m] \033[1;32mYour email: \033[1;33m "+set_name+"-darkenpasiya"+"@"+mail)
		print("\033[1;34m[\033[1;31m*\033[1;34m] \033[1;36mCTRL+ C \033[1;31mto stopped..\033[1;37m")
		_ = int(os.get_terminal_size().columns/2)
		print("╍"*os.get_terminal_size().columns + '\n')
		run(set_name+"-darkenpasiya"+"@"+mail)
	elif pil in ["00","0"]:
		print("")
		exit("\033[1;34m[\033[1;36m\033[1;36m=\033[1;34m] \033[1;31mExit program, \033[1;33mHave A Nice Day..\n")
	else:
		print()
		exit('\033[1;34m[\033[1;31m-\033[1;34m] \033[1;31mWrong Choise, \033[1;33mexit..')

if __name__ == "__main__":
	main()

