#!/bin/python
# Tempory Mail
try:
	import requests as r, random, json, os
	from time import sleep
except ModuleNotFoundError:
	exit("[!] Module not installed")

list_mail = ["labworld.org","vintomaper.com","mentonit.net"]
url = "https://cryptogmail.com/"
num = 0

def get_teks(accept, key):
	cek = r.get(url+"api/emails/"+key, headers={"accept": accept}).text
	if "error" in cek:
		return "-"
	else:
		return cek.strip()

def get_random(digit):
	lis = list("abcdefghijklmnopqrstuvwxyz0123456789")
	dig = [random.choice(lis) for _ in range(digit)]
	return "".join(dig), random.choice(list_mail)

def animate(teks):
	lis = list("╣╩╠╦")
	for cy in lis:
		print("\r\033[1;34m[\033[1;33m"+cy+"\033[1;34m] "+str(teks)+".. ", end="")
		sleep(0.5)

def run(email):
	while True:
		try:
			animate("\033[1;35mWaiting for incoming message")
			raun = r.get(url+"api/emails?inbox="+email).text
			if "404" in raun:
				continue
			elif "data" in raun:
				z = json.loads(raun)
				for data in z["data"]:
					print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mID: \033[1;33m"+data["id"], end="\n")
					got = json.loads(r.get(url+"api/emails/"+data["id"]).text)
					pengirim = got["data"]["sender"]["display_name"]
					email_pe = got["data"]["sender"]["email"]
					subject  = got["data"]["subject"]
					print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mSender Name: \033[1;33m"+pengirim, end="\n")
					print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mSender mail: \033[1;33m"+email_pe, end="\n")
					print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mSubject    : \033[1;33m"+subject, end="\n")
					print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mMessage    :\033[1;33m "+get_teks("text/html,text/plain",data["id"]), end="\n")
					atc = got["data"]["attachments"]
					if atc == []:
						print("\r\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mattachments: -\033[1;33m", end="\n")
					else:
						print("[•] attachments: ")
						for atch in atc:
							id = atch["id"]
							name = atch["file_name"]
							name = name.split(".")[-1]
							svee = r.get("https://cryptogmail.com/api/emails/"+data["id"]+"/attachments/"+id)
							open(id+"."+name, "wb").write(svee.content)
							print("      ~ "+id+"."+name)
					print("-"*45)
					r.delete(url+"api/emails/"+data["id"])
				continue
			else:
				continue
		except (KeyboardInterrupt,EOFError):
				exit("\n\033[1;34m[\033[1;32m✓\033[1;34m] \033[1;32mProgram finished, \033[1;33mexiting...\n")


def main():
	os.system('clear')
	global num
	print("""
\033[1;31m ▄▄▄▄▄▄▄ ▄▄▄▄▄▄▄ ▄▄   ▄▄ ▄▄▄▄▄▄▄ ▄▄▄▄▄▄▄ ▄▄▄▄▄▄   ▄▄▄▄▄▄ ▄▄▄▄▄▄   ▄▄   ▄▄
\033[1;31m█       █       █  █▄█  █       █       █   ▄  █ █      █   ▄  █ █  █ █  █
\033[1;31m█▄     ▄█    ▄▄▄█       █    ▄  █   ▄   █  █ █ █ █  ▄   █  █ █ █ █  █▄█  █
\033[1;31m  █   █ █   █▄▄▄█       █   █▄█ █  █ █  █   █▄▄█▄█ █▄█  █   █▄▄█▄█       █
\033[1;31m  █   █ █    ▄▄▄█       █    ▄▄▄█  █▄█  █    ▄▄  █      █    ▄▄  █▄     ▄█
\033[1;31m  █   █ █   █▄▄▄█ ██▄██ █   █   █       █   █  █ █  ▄   █   █  █ █ █   █
\033[1;31m  █▄▄▄█ █▄▄▄▄▄▄▄█▄█   █▄█▄▄▄█   █▄▄▄▄▄▄▄█▄▄▄█  █▄█▄█ █▄▄█▄▄▄█  █▄█ █▄▄▄█

			\033[1;36m ▄▄   ▄▄ ▄▄▄▄▄▄ ▄▄▄ ▄▄▄
			\033[1;36m█  █▄█  █      █   █   █
			\033[1;36m█       █  ▄   █   █   █
			\033[1;36m█       █ █▄█  █   █   █
			\033[1;36m█       █      █   █   █▄▄▄
			\033[1;36m█ ██▄██ █  ▄   █   █       █
			\033[1;36m█▄█   █▄█▄█ █▄▄█▄▄▄█▄▄▄▄▄▄▄█

			\033[1;31m[\033[1;32m+\033[1;31m] \033[1;33mAuthor \033[1;34m: \033[1;35mDarken-Pasiya
			\033[1;31m[\033[1;32m+\033[1;31m] \033[1;33mThanks \033[1;34m: \033[1;35mRiski Darmawan


\033[1;34m┏━━\033[1;32m▶\033[1;34m[\033[1;37;41m01\033[0m\033[1;34m] \033[1;33mGET RANDOM EMAIL
\033[1;34m┃
\033[1;34m┣━━\033[1;32m▶\033[1;34m[\033[1;37;41m02\033[0m\033[1;34m] \033[1;33mGET CUSTOM EMAIL
\033[1;34m┃
\033[1;34m┗━━\033[1;32m▶\033[1;34m[\033[1;37;41m00\033[0m\033[1;34m] \033[1;37mEXIT\033[0m
""")

	pil = input("~\033[1;32m/$\033[1;37m@\033[1;36mroot\033[1;37m@\033[1;36mTemporary-Mail\033[1;37m~\033[1;33m>\033[1;37m ")
	while pil == "" or not pil.isdigit():
		pil = input("~\033[1;32m/$\033[1;37m@\033[1;36mroot\033[1;37m@\033[1;36mTemporary-Mail\033[1;37m~\033[1;33m>\033[1;37m ")
	if pil in ["01","1"]:
		set_name, set_email = get_random(10)
		print("\n\033[1;34m[\033[1;32m*\033[1;34m] \033[1;32mYour email: \033[1;33m darken-pasiya-"+set_name+"@"+set_email)
		print("\033[1;34m[\033[1;31m*\033[1;34m] \033[1;36mCTRL+ C \033[1;31mto stopped..\033[1;37m")
		print("-"*45)
		run("darken-pasiya-"+set_name+"@"+set_email)
	elif pil in ["02","2"]:
		set_name = input("\033[1;34m[\033[1;32m•\033[1;34m] \033[1;32mSet mail name:\033[1;36m ")
		print()
		for cy in list_mail:
			num += 1
			print(" "*5,"\033[1;34m[\033[1;32m"+str(num)+"\033[1;34m]\033[1;33m @"+cy)
		print()
		set_email = input("\033[1;34m[\033[1;33m?\033[1;34m] \033[1;35mSelect: \033[1;36m")
		while set_email == "" or not set_email.isdigit() or int(set_email) > len(list_mail):
			set_email = input("\033[1;34m[\033[1;33m?\033[1;34m] \033[1;35mSelect:\033[1;36m ")
		mail = list_mail[int(set_email)-1]
		print("\n\033[1;34m[\033[1;32m*\033[1;34m] \033[1;32mYour email: \033[1;33m darken-pasiya-"+set_name+"@"+mail)
		print("\033[1;34m[\033[1;31m*\033[1;34m] \033[1;36mCTRL+ C \033[1;31mto stopped..\033[1;37m")
		print("-"*45)
		run("darken-pasiya-"+set_name+"@"+mail)
	elif pil in ["00","0"]:
		exit("\033[1;34m[\033[1;36m\033[1;36m=\033[1;34m] \033[1;31mExit program, \033[1;33mHave A Nice Day..\n")
	else:
		exit("\033[1;34m[\033[1;31m-\033[1;34m] \033[1;31mWrong Choise, \033[1;33mexit..\n")


if __name__ == "__main__":
	main()

